{% set version = "1.0.0rc2" %}

package:
  name: sphinx-book-theme
  version: {{ version }}

source:
  - url: https://pypi.io/packages/py3/s/sphinx-book-theme/sphinx_book_theme-{{ version }}-py3-none-any.whl
    sha256: 43977402f55b79706e117c6de6f50e67dac6dad698eb9b75be07dc2e6a689bde
  - folder: src
    url: https://github.com/executablebooks/sphinx-book-theme/archive/refs/tags/v{{ version }}.tar.gz
    sha256: b871187ce98ca07f4fce94f9736af7ca6c4785d507cfd040b59c159e0630b29d

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install --find-links . --no-index --ignore-installed --no-deps sphinx-book-theme

requirements:
  host:
    - pip
    - python >=3.7
    - sphinx_theme_builder
  run:
    - pydata-sphinx-theme >=0.13.0rc4
    - python >=3.7
    - pyyaml
    - sphinx >=4,<7

test:
  source_files:
    - src/tests
  imports:
    - sphinx_book_theme
  commands:
    - pip check
    - cd src
    - pytest -vv --cov=sphinx_book_theme --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=90
  requires:
    - myst-nb >=0.13.2
    - pip
    - pytest-cov
    - pytest-regressions
    - pytest >=6.0.1,<6.1.0
    - sphinx-thebe

about:
  home: https://sphinx-book-theme.readthedocs.org
  summary: A clean book theme for scientific explanations and documentation with Sphinx
  dev_url: https://github.com/executablebooks/sphinx-book-theme
  license: BSD-3-Clause
  license_file: src/LICENSE

extra:
  recipe-maintainers:
    - anirrudh
    - conda-forge/jupyter-book
