# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 1.1.4

package:
  name: sphinx-book-theme
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/py3/s/sphinx-book-theme/sphinx_book_theme-${{ version }}-py3-none-any.whl
    sha256: 843b3f5c8684640f4a2d01abd298beb66452d1b2394cd9ef5be5ebd5640ea0e1
  - url: https://github.com/executablebooks/sphinx-book-theme/archive/refs/tags/v${{ version }}.tar.gz
    sha256: e845ce8e58c99ab858fae82b4bbbc62bde226dd861c90ba1f91a26e1113a5775
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install --find-links . --no-index --ignore-installed --no-deps sphinx-book-theme

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - pydata-sphinx-theme ==0.15.4
    - python >=${{ python_min }}
    - sphinx >=6.1

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports:
        - sphinx_book_theme
  - files:
      recipe:
        - run_test.py
      source:
        - src/tests/
    requirements:
      run:
        - beautifulsoup4
        - coverage
        - defusedxml
        - myst-nb
        - pytest
        - pytest-regressions
        - python ${{ python_min }}.*
        - sphinx-thebe
    script:
      - python run_test.py

about:
  summary: A clean book theme for scientific explanations and documentation with Sphinx
  license: BSD-3-Clause
  license_file: src/LICENSE
  homepage: https://sphinx-book-theme.readthedocs.org
  repository: https://github.com/executablebooks/sphinx-book-theme

extra:
  recipe-maintainers:
    - anirrudh
    - conda-forge/jupyter-book
